### ISSUE TITLE
Question about Data Processing for BP4D and DISFA Datasets  

### ISSUE THREAD

**Issue by laura990501** [ihp-lab/FG-Net#3]
Hi Yufeng,  

Thank you so much for open-sourcing your amazing work! I’m trying to reproduce your results, but I’m a bit confused about the “Data Structure” part related to dataset preparation. Specifically, I’m unsure how to process the BP4D and DISFA datasets to match your requirements.  

Would it be possible for you to share:  
1. The exact steps and scripts for processing these datasets?  
2.  if feasible, could you upload the processed versions of the datasets?  

Your help would be greatly appreciated, and thank you again for sharing this valuable project!

**Comment by yufengyin** [comment]
Hi Jiayi,

Sorry for the late reply since I am on vacation. Thank you for your interests in our work!

1. We release the face cropping codes in the following link. https://github.com/ihp-lab/SEMPI/blob/main/data/engagement/code/utils.py

This one is exactly the same as the one used for BP4D and DISFA processing. For usage, please check: https://github.com/ihp-lab/SEMPI/blob/main/data/engagement/code/crop_face.py

2. We cannot release the data due to the license issues of the two datasets. Sorry about that.

Let me know if you have any further questions.

**Comment by laura990501** [comment]
Thank you so much!
